name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.4.2'
      - name: Build
        run: nimble build --accept
        # env:
        #   ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.4.2'
      - name: Test Project
        run: nimble test --accept
        # env:
        #   ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

