name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: jiro4989/setup-nim-action@latest
      - name: Build
        run: nimble build --accept
  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - uses: jiro4989/setup-nim-action@latest
      - name: Test Project
        run: nimble test --accept

